---
- src: https://github.com/elastic/ansible-elasticsearch.git
  scm: git
  version: master
  name: elastic.elasticsearch
- src: https://github.com/geerlingguy/ansible-role-kibana.git
  scm: git
  version: master
  name: geerlingguy.kibana
 
